### ISSUE TITLE
Should be able to search all public projects in ref builder

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#124]
Prism helpers aren't searchable in the ref builder, we should expose all public projects in the ref builder, and then add stoplight specific ones first.

@lottamus and @casserni does this make sense?

**Comment by marbemac** [comment]
We had this before and scared people to see tons of projects unrelated to
them. Hmm, thoughts?

On Jan 9, 2018 11:21 AM, "Thomas Pytleski" <notifications@github.com> wrote:

Prism helpers aren't searchable in the ref builder, we should expose all
public projects in the ref builder, and then add stoplight specific ones
first.

@lottamus <https://github.com/lottamus> and @casserni
<https://github.com/casserni> does this make sense?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/stoplightio/desktop/issues/124>, or mute the thread

**Comment by pytlesk4** [comment]
At the very least, we need to surface our Stoplight Prism Helpers, because you can't set up prism mock instance without knowing the export link to prism helpers. I have some ideas around this, but we can take this offline.

**Comment by lottamus** [comment]
Yeah I agree with allowing to search any public projects but maybe not right now. At the very least we should include the official Stoplight resources (IE: prism helpers, todos spec, etc) available when selecting "reference from another project"

**Comment by marbemac** [comment]
Closing this in favor of the mapping proposal.
