### ISSUE TITLE
Guest of an org get read access to all projects in an org

### ISSUE THREAD

**Issue by pytlesk4** [stoplightio/desktop#125]
@marbemac customer brought this up to me, and I didn't realize this was how acl works, is this accurate?

**Comment by marbemac** [comment]
There are no org guests, there are org members. And yeah org members can
read projects in the org. It's intended. We plan to add guest role to
projects, so that one could grant read access to a specific project without
making the user an org member.

On Jan 9, 2018 11:21 AM, "Thomas Pytleski" <notifications@github.com> wrote:

Assigned #125 <https://github.com/stoplightio/desktop/issues/125> to
@marbemac <https://github.com/marbemac>.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/stoplightio/desktop/issues/125#event-1415992032>, or mute
the thread

**Comment by pytlesk4** [comment]
Was this always the case? Or is this because of the switch to git?
