### ISSUE TITLE
Path parameters can be defined in two places

### ISSUE THREAD

**Issue by wvzuilen** [stoplightio/desktop#126]
Discovered in the Next UI:

When I set a new path with a path parameter, it looks like I could define the path parameter in two places:

1:
<img width="476" alt="schermafbeelding 2018-01-10 om 16 22 58" src="https://user-images.githubusercontent.com/26225750/34780133-910363ec-f622-11e7-9ad1-716cfb5f151e.png">

2:
<img width="1063" alt="schermafbeelding 2018-01-10 om 16 13 10" src="https://user-images.githubusercontent.com/26225750/34779814-90360e2a-f621-11e7-9ade-09404e9e6d60.png">

In addition: why is there a 'parameters' submenu-item being created when I set a path parameter variable in de path url? The parameters could be set in the usual place (nr. 2), aren't they?

**Comment by marbemac** [comment]
Hi @wvzuilen, OpenAPI (Swagger 2) allows you to define parameters at the path level, or at the operation level. The recommended approach is to define them at the path level, since those parameters (and there descriptions, etc) will be applied to all operations defined in the path. We do this for you by default when you add/remove path parameters.

You can fine more info about parameters in OAS in the path specification: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#pathItemObject

Closing, as I don't think this is an issue in Stoplight itself, but let me know if you have any more questions about this!

**Comment by wvzuilen** [comment]
Ok, clear. Thanks for explanation. Possibly you could consider to clarify the difference by adding 'path level' / 'operation level' or something like that.
