### ISSUE TITLE
UI bug : not all people are displayed

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#165]
If an organization contains more than 25 people, only the first 25 people are displayed in the table.
There is no pagination system and the search box doesn't search in the full database.

Could you add a "Load more" button, just like issue #155, please ?

**Comment by lottamus** [comment]
Yes we will add the load more button to all the list pages until we have better support for pagination.

**Comment by MCalder-j2** [comment]
I have at least 4 people in my org that cannot see any of our specs because of this.  The problem is compounded by the Guest role bug where guests can't see specs.  Can you please expedite the resolution for this?

**Comment by marbemac** [comment]
Yup it's been prioritized and is being worked on today (both the member list length issue and the guest role issue).

@MCalder-j2 for the guest role we are going to only show public projects or private projects that guests have been granted read access to (instead of all projects in the organization) - does that work OK for you? In talking with some other customers, this seems to be most useful application of the guest role (as opposed to member role, which can read all projects by default).

**Comment by lottamus** [comment]
We've released a temporary fix by bumping the list limit to 100 members. If this is too low, we can bump it again. We are currently working on pagination which will completely solve this issue.

I have opened a new issue for the guest bug: https://github.com/stoplightio/desktop/issues/168

**Comment by ntiss** [comment]
Hi @lottamus, thanks for the bump. That suits me perfectly.

**Comment by MCalder-j2** [comment]
That works for us as well. Thanks for the quick work around.
