### ISSUE TITLE
CORS issue on web app and desktop app (503 error)

### ISSUE THREAD

**Issue by bios21** [stoplightio/desktop#208]
Hello,

I'm getting some 503 errors because of CORS when getting `data` from `api.stoplight.io`, the first OPTION request fail with this info:
<details>
<pre>
Failed to load https://api.stoplight.io/organizations/au7hjRahZ9ufAu9GA/data:
Response to preflight request doesn't pass access control check:
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'https://app.stoplight.io' is therefore not allowed access. The response had HTTP status code 503.
</pre>

<a href="https://user-images.githubusercontent.com/5783789/39804047-ae40d87a-537b-11e8-8eb4-40d117eeb8a7.png"><img src="https://user-images.githubusercontent.com/5783789/39804047-ae40d87a-537b-11e8-8eb4-40d117eeb8a7.png"/></a>
</details>

On the other hand, others requests (i.e. `api-iam`) and even websockets, are not failing.

This happen both in web and desktop app.  
And I'm only trying to login.

Any idea?

**Comment by rossmcdonald** [comment]
@bios21 This was caused by an [incident](http://status.stoplight.io/incidents/lfvhvwvwk5fk) on Stoplight Classic that occurred earlier this morning that prevented requests from returning properly. The issue was resolved roughly an hour ago, so requests should now be completing successfully. Let us know if you encounter any other errors.

**Comment by bios21** [comment]
I can confirm that everything is back to perfect.
Thank you <3
