### ISSUE TITLE
Trailing 0's removed when type set to string

### ISSUE THREAD

**Issue by tatiana-perry** [stoplightio/desktop#275]
When trying to create an object model, setting the type to string and the value to "54.000" or "0.0000", it removed the trailing 0's and also removes "0.000" from the example response. 

<img width="635" alt="screen shot 2018-08-08 at 8 38 22 am" src="https://user-images.githubusercontent.com/16635677/43841123-079fd7a0-9ae8-11e8-80c6-4d646b3c70a4.png">

Setting this in the visual editor or in the raw schema, it reverts back to integer format and removes extra 0's. 

Expected: When type set to a string, display's whatever information is in the string. Regardless of letters or numbers. 
Actual:
Trailing 0's are removed and is formatted as a number in the raw schema, even when type set to string. 

Was able to recreate using both imported OAS file and starting from scratch. 

![2018-08-08 09_07_09](https://user-images.githubusercontent.com/16635677/43842212-77443f4a-9aea-11e8-8cef-6a92c3d01d3f.gif)

**Comment by tatiana-perry** [comment]
Tried adding a space before and after the number, but it does not work either. It should respect whatever text is between the string formatting.

**Comment by lottamus** [comment]
Good find! It looks like that input is seeing it as a "number" rather than a "string". 

A work around is to wrap the example with double quotes `"54.000"`. 

You can enter this value into the input field using quotes and it will give you this schema

```
{
  "type": "object",
  "properties": {
    "price_ex_tax": {
      "type": "number",
      "example": "54.000"
    }
  }
}
```

![image](https://user-images.githubusercontent.com/7423098/43856622-a9e292fc-9b0e-11e8-9077-432c803d3578.png)

**Comment by tatiana-perry** [comment]
Nice!!
