### ISSUE TITLE
Set up template for new issues on github

### ISSUE THREAD

**Issue by usmanovbf** [stoplightio/desktop#292]
Do it [here](https://github.com/stoplightio/desktop/issues/templates/edit) . Add least custom two templates for Bug and Feature Request

**Comment by tbarn** [comment]
Hey @usmanovbf, we have plans to do this. But I also wanted to drop a note about https://community.stoplight.io. We are encouraging users to post feature requests there instead since Stoplight Next accounts are connected to the forum.

**Comment by tbarn** [comment]
Just wanted to share an update on this issue: Originally I had plans to make this happen, but over the next couple of months we will be moving away from GitHub Issues and encouraging the use of the [forum](http://community.stoplight.io) where others share bugs, support questions, feature requests, etc. So I will be closing this issue for now since we will encourage users to go use the forum instead.
