### ISSUE TITLE
Coverage always displayed as 0%

### ISSUE THREAD

**Issue by russmilburn** [stoplightio/desktop#35]
When running some scenarios against an API spec. The test run successfully but coverage is always displayed as 0%

**Comment by marbemac** [comment]
Hi Russ, there are a couple of possibilities here. The main one that comes to mind is that right now the coverage report requires status code assertions to be set in the tests tab.

Could you try adding a status code assertion in one of your steps and re-running the whole collection?

In general contract testing should also be accompanied by a status code assertion, because the contract test just makes sure that the response returned validates against the spec for the status code returned. So if you get a 404 response, and the response body validates against the 404 response in your spec, contract testing will pass. But you might actually want a 200 response. This is why most tests should be status code assertion + the automatic contract testing that's built in.

We plan to make this more obvious and intuitive soon!

**Comment by russmilburn** [comment]
There are already status code assertions in the tests. they only check for the 200 success code

**Comment by marbemac** [comment]
Closed it because we figured out the issue in a separate channel! Invalid basePath in the Swagger specification.
