### ISSUE TITLE
problem with target Host dropdown list

### ISSUE THREAD

**Issue by ntiss** [stoplightio/desktop#69]
![issue_targethost](https://user-images.githubusercontent.com/29988779/32680728-544dcd74-c66c-11e7-8308-3e2a49bf40ed.gif)

**Comment by marbemac** [comment]
@ChrisNLott this one is partially fixed with the updated hosts handling. We just need a variable replacement pass before initializing the collection editor. Additionally, we need to account for changes to environment variables after the editor is loaded.

<img width="1008" alt="screen shot 2017-11-10 at 4 43 07 pm" src="https://user-images.githubusercontent.com/847542/32681714-6269251a-c636-11e7-9156-7205537ee60b.png">

**Comment by marbemac** [comment]
Deployed last night.
