### ISSUE TITLE
Setting Faker attributes in Stoplight breaks Spec in Scenarios

### ISSUE THREAD

**Issue by knightstick** [stoplightio/desktop#8]
When setting Faker values for Models, for example, 
```
"first-name": {
  "type": "string",
  "faker": "name.firstName"
```
on a User model, the "Spec" in Scenarios is no longer valid (as the faker key is not permitted in the OpenAPI specification).

As a work-around, I can "clean" the local file for the Scenario spec by removing these lines (and the preceding comma), but, it would be nice if it was either ignored, or auto-cleaned.

![image](https://cloud.githubusercontent.com/assets/5941208/23884691/5a0ce154-08c2-11e7-81b7-dc53b1642215.png)

**Comment by marbemac** [comment]
Try "x-faker" for now, instead of "faker".

We are actually going to be removing faker support in the next major version of Prism (the version that we will be open sourcing). Instead of faker, we would recommend that you use chance js. Chance is already supported in Prism, and we will continue to support it.

You can use chance with x-chance properties, and it functions very similarly to faker. The reason for the change is because faker is ~1mb all in, and chance is ~160kb.

http://chancejs.com

**Comment by knightstick** [comment]
"x-chance" seems to work just fine - We were only using it to generate examples, so, no big deal. Thanks for the reply @marbemac, I'm happy to consider this resolved 👌
