### ISSUE TITLE
Unable to edit object attributes (e.g. validations)

### ISSUE THREAD

**Issue by johnmckinzie** [stoplightio/desktop#80]
It appears an update may have removed the ability to edit certain aspects of object attributes (e.g. validations). When I click on the edit icon for an attribute, I'm only presented with **Default Value** and **Description**.

![Edit Attribute UI](https://user-images.githubusercontent.com/2511456/33078519-e9c77346-cea0-11e7-820e-0fbe35e00765.png)

**Comment by marbemac** [comment]
Hi @johnmckinzie we have split up the property parts into different areas, because as we continue to add support for more JSON Schema / Swagger features, the kitchen sink pane was becoming unmanageable. You can access the default / description by clicking the pencil icon, types selector by clicking on the type, validations by clicking on the validations (on the right side there), etc.

Let me know if any of that does not work for you.

**Comment by johnmckinzie** [comment]
Okay. It works. I didn't pick up on that in the overnight release. Thanks.

**Comment by marbemac** [comment]
No problem - we're working on a little changelog widget - to appear in the top right of the screen - that will help point out these updates as we deploy them.
